---
env:
    name: Hopper-v3
    # reward_clip: 10

model:
    actor:
        units_list: [256, 256]
        norm: null
        activation: relu
        LOG_STD_MIN: -20
        LOG_STD_MAX: 2
    q:
        units_list: [256, 256]
        norm: null
        activation: relu
    temperature:
        temp_type: constant
        value: .2

agent:
    algorithm: &algo sac
    replay_type: &replay uniform
    gamma: &gamma .99
    batch_size: &bs 100
    n_steps: &nsteps 3
    polyak: .995

    act_eps: 0
    eval_act_eps: 0

    MAX_STEPS: 3e6
    TRAIN_PERIOD: 50
    LOG_PERIOD: 5000
    EVAL_PERIOD: 5000
    N_UPDATES: 50
    N_EVAL_EPISODES: 1
    # RECORD: True

    tbo: False

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    # arguments for optimizer
    opt_name: adam
    schedule_lr: False
    actor_lr: 1e-3
    value_lr: 1e-3
    temp_lr: 3e-4
    # clip_norm: 10
    
    # arguments for PER
    per_alpha: .5
    per_epsilon: 1.e-4

replay:
    replay_type: *replay
    seqlen: 10
    # arguments for PER
    beta0: .4
    beta_steps: 5e4
    to_update_top_priority: True

    # arguments for general replay
    n_steps: *nsteps
    gamma: *gamma
    batch_size: *bs
    min_size: 1e4
    capacity: 1e6
    has_next_obs: False
